#!/usr/bin/env python3
"""Generates Ring Studio's data files from the docs, so the studio's guided fixes (C14) and the test runner (F26)
always match docs/09-troubleshooting.md and docs/07-test-and-demo-plan.md.

Run: python tools/gen_docs_data.py   (also run by tools/build_ui.py)
Writes ui/src/js/data/fixes.js and ui/src/js/data/tests.js
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ui" / "src" / "js" / "data"
FAMILY = {"W": "Power and wiring", "F": "Firmware", "S": "Sensor health", "P": "Placement, angle and distance",
          "B": "Background and surroundings", "N": "Noise and interference", "H": "Hand profile", "A": "Accuracy and behaviour",
          "L": "LED ring", "U": "Wi-Fi and Ring Studio"}


def parse_fixes(md: str):
    fixes = {}
    # sections: ### CODE · title  (Kind: detail)
    pattern = re.compile(r"^### ([A-Z]\d{1,2}) · (.+?)\s*(?:\((Auto|Symptom|Studio-guided)(?::\s*(.*?))?\))?\s*$", re.M)
    matches = list(pattern.finditer(md))
    for i, m in enumerate(matches):
        code, title, kind, detail = m.group(1), m.group(2).strip(), (m.group(3) or "").strip(), (m.group(4) or "").strip()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(md)
        body = md[m.end():end]
        body = re.split(r"^## ", body, maxsplit=1, flags=re.M)[0]      # stop at the next family heading
        body = body.replace("\n---\n", "\n").strip()
        fixes[code] = {"code": code, "title": title, "family": FAMILY.get(code[0], code[0]), "kind": kind or "Symptom", "detect": detail, "body": body}
    # symptom finder
    symptoms = []
    sec = md.split("## 1. Symptom finder", 1)[1].split("## 2.", 1)[0]
    for line in sec.splitlines():
        if not line.startswith("|") or line.startswith("|---") or "What you see" in line:
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        codes = re.findall(r"\b([A-Z]\d{1,2})(?:\s+to\s+([A-Z]\d{1,2}))?", cells[1])
        expanded = []
        for a, b in codes:
            if b and a[0] == b[0]:
                expanded += [f"{a[0]}{n}" for n in range(int(a[1:]), int(b[1:]) + 1)]
            else:
                expanded.append(a)
        symptoms.append({"see": cells[0].replace("**", ""), "codes": expanded, "note": "Unplug everything now" if "Unplug" in cells[1] else ""})
    # techniques section
    tech = md.split("## 2. Three techniques used throughout", 1)[1].split("\n## ", 1)[0].strip()
    return fixes, symptoms, tech


def parse_tests(md: str):
    tests = []
    for line in md.splitlines():
        m = re.match(r"^\| (T\d{1,2}) \| (\d) \| (.+?) \| (.+?) \|\s*$", line)
        if not m:
            continue
        tid, phase, proc, expect = m.groups()
        title = re.match(r"\*\*(.+?)\*\*", proc)
        tests.append({"id": tid, "n": int(tid[1:]), "phase": int(phase), "title": (title.group(1).rstrip(":") if title else proc.split(".")[0][:70]),
                      "procedure": proc, "expected": expect})
    tests.sort(key=lambda t: t["n"])
    return tests


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    fixes, symptoms, tech = parse_fixes((ROOT / "docs" / "09-troubleshooting.md").read_text(encoding="utf-8"))
    tests = parse_tests((ROOT / "docs" / "07-test-and-demo-plan.md").read_text(encoding="utf-8"))
    (OUT / "fixes.js").write_text("/* Generated by tools/gen_docs_data.py from docs/09-troubleshooting.md. Do not edit. */\n"
                                  "var RS = globalThis.RS || (globalThis.RS = {});\n"
                                  f"RS.FIXES = {json.dumps(fixes, ensure_ascii=False, indent=0)};\n"
                                  f"RS.SYMPTOMS = {json.dumps(symptoms, ensure_ascii=False)};\n"
                                  f"RS.TECHNIQUES = {json.dumps(tech, ensure_ascii=False)};\n", encoding="utf-8")
    (OUT / "tests.js").write_text("/* Generated by tools/gen_docs_data.py from docs/07-test-and-demo-plan.md. Do not edit. */\n"
                                  "var RS = globalThis.RS || (globalThis.RS = {});\n"
                                  f"RS.TESTS = {json.dumps(tests, ensure_ascii=False, indent=0)};\n", encoding="utf-8")
    print(f"fixes: {len(fixes)} codes, {len(symptoms)} symptoms; tests: {len(tests)}")


if __name__ == "__main__":
    main()
